config/routes.rb
Rails.application.routes.draw do
  resources :colaborators
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/colaborator.rb
class Colaborator < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colaborators_controller.rb
class ColaboratorsController < ApplicationController
  before_action :set_colaborator, only: %i[ show edit update destroy ]

  # GET /colaborators or /colaborators.json
  def index
    @colaborators = Colaborator.all
  end

  # GET /colaborators/1 or /colaborators/1.json
  def show
  end

  # GET /colaborators/new
  def new
    @colaborator = Colaborator.new
  end

  # GET /colaborators/1/edit
  def edit
  end

  # POST /colaborators or /colaborators.json
  def create
    @colaborator = Colaborator.new(colaborator_params)

    respond_to do |format|
      if @colaborator.save
        format.html { redirect_to colaborator_url(@colaborator), notice: "Colaborator was successfully created." }
        format.json { render :show, status: :created, location: @colaborator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @colaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaborators/1 or /colaborators/1.json
  def update
    respond_to do |format|
      if @colaborator.update(colaborator_params)
        format.html { redirect_to colaborator_url(@colaborator), notice: "Colaborator was successfully updated." }
        format.json { render :show, status: :ok, location: @colaborator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @colaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaborators/1 or /colaborators/1.json
  def destroy
    @colaborator.destroy

    respond_to do |format|
      format.html { redirect_to colaborators_url, notice: "Colaborator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colaborator
      @colaborator = Colaborator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def colaborator_params
      params.require(:colaborator).permit(:name, :email, :direction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colaborators_helper.rb
module ColaboratorsHelper
end

app/views/colaborators/_colaborator.html.erb
<div id="<%= dom_id colaborator %>">
  <p>
    <strong>Name:</strong>
    <%= colaborator.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= colaborator.email %>
  </p>

  <p>
    <strong>Direction:</strong>
    <%= colaborator.direction %>
  </p>

</div>

app/views/colaborators/_form.html.erb
<%= form_with(model: colaborator) do |form| %>
  <% if colaborator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(colaborator.errors.count, "error") %> prohibited this colaborator from being saved:</h2>

      <ul>
        <% colaborator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :direction, style: "display: block" %>
    <%= form.text_field :direction %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/colaborators/edit.html.erb
<h1>Editing colaborator</h1>

<%= render "form", colaborator: @colaborator %>

<br>

<div>
  <%= link_to "Show this colaborator", @colaborator %> |
  <%= link_to "Back to colaborators", colaborators_path %>
</div>

app/views/colaborators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Colaborators</h1>

<div id="colaborators">
  <% @colaborators.each do |colaborator| %>
    <%= render colaborator %>
    <p>
      <%= link_to "Show this colaborator", colaborator %>
    </p>
  <% end %>
</div>

<%= link_to "New colaborator", new_colaborator_path %>

app/views/colaborators/new.html.erb
<h1>New colaborator</h1>

<%= render "form", colaborator: @colaborator %>

<br>

<div>
  <%= link_to "Back to colaborators", colaborators_path %>
</div>

app/views/colaborators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @colaborator %>

<div>
  <%= link_to "Edit this colaborator", edit_colaborator_path(@colaborator) %> |
  <%= link_to "Back to colaborators", colaborators_path %>

  <%= button_to "Destroy this colaborator", @colaborator, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColaboradoresRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>